[package]
name = "salak"
version = "0.1.0"
authors = ["Daniel Yu <leptonyu@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
description = "A rust configuration loader"
documentation = "https://docs.rs/salak/"
repository = "https://github.com/leptonyu/salak.rs"
homepage = "https://github.com/leptonyu/salak.rs"
readme = "README.md"
exclude = [
    "app.toml",
]

[dependencies]
lazy_static = "1.4"
regex = {version= "1.4", optional=true}
clap = {version= "2.33", optional=true}
toml = {version= "0.5", optional=true}
log = {version="0.4", optional=true}

[dev-dependencies]
quickcheck = "1"
quickcheck_macros ="1"
env_logger= "0.8"

[features]
default = ["enable_args", "enable_toml", "enable_log"]
enable_toml = ["toml"]
enable_args = ["clap", "regex"]
enable_log = ["log"]