[package]
name = "salak"
version = "0.1.0"
authors = ["Daniel Yu <leptonyu@gmail.com>"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
log = "0.4"
clap = "3.0.0-beta.2"
lazy_static= "1.4"
regex = "1.4"
