[package]
name = "salak"
version = "0.6.0"
authors = ["Daniel Yu <leptonyu@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A rust configuration loader"
documentation = "https://docs.rs/salak/"
repository = "https://github.com/leptonyu/salak.rs"
homepage = "https://github.com/leptonyu/salak.rs"
readme = "README.md"
keywords = [
    "configuration",
    "config",
    "settings",
    "env",
    "environment"
]
categories = ["config"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
[package.metadata.playground]
all-features = true

[dependencies]
lazy_static = "^1.4"
regex = {version= "^1.4", optional=true}
clap = {version= "^2.33", optional=true}
toml = {version= "^0.5", optional=true}
log = {version="^0.4", optional=true}
yaml-rust = {version="^0.4.5", optional=true}
salak_derive = { path = "./salak_derive", version = "^0.2", optional = true }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros ="1"
env_logger= "0.8"

[features]
default = ["enable_derive", "enable_toml", "enable_log"]
enable_toml = ["toml"]
enable_clap = ["clap", "regex"]
enable_log = ["log"]
enable_derive = ["salak_derive"]
enable_yaml = ["yaml-rust"]

[workspace]
members = [".", "salak_derive"]

[[example]]
name = "salak"
required-features = ["default", "enable_clap"]
