[package]
name = "salak"
version = "0.1.0"
authors = ["Daniel Yu <leptonyu@gmail.com>"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
lazy_static= "1.4"
regex = "1.4"
clap = {version="2.33", optional=true}
toml = {version= "0.5", optional=true}

[dev-dependencies]
quickcheck = "1"
quickcheck_macros ="1"

[features]
default = ["enable_args", "enable_toml"]
enable_toml = ["toml"]
enable_args = ["clap"]