[package]
authors = ['Daniel Yu <leptonyu@gmail.com>']
categories = ['config']
description = 'Salak factory to package initialization.'
documentation = 'https://docs.rs/salak_factory/'
edition = '2018'
homepage = 'https://github.com/leptonyu/salak.rs'
keywords = [
  'configuration',
  'config',
  'settings',
  'env',
  'environment',
]
license = 'MIT'
name = 'salak_factory'
readme = 'README.md'
repository = 'https://github.com/leptonyu/salak.rs'
version = '0.3.0'
[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
  '--cfg',
  'docsrs',
]

[package.metadata.playground]
all-features = true

[dependencies]
humantime = {optional = true, version = '^2'}
log = {optional = true, version = '^0.4'}
postgres = {optional = true, version = '0.19'}
r2d2 = {optional = true, version = '^0.8'}
redis = {optional = true, version = '0.20'}
rtrb = {optional = true, version = '^0.1'}
salak = {path = '..', version = '^0.9'}
scheduled-thread-pool = {optional = true, version = '^0.2'}
tracing = {optional = true, version = '^0.1'}
tracing-log = {optional = true, version = '^0.1'}
tracing-subscriber = {optional = true, version = '^0.2'}

[dev-dependencies]
chrono = "0.4"
env_logger = "0.8"
fast_log = "1"
fern = "0.6"
log4rs = "1"
num_cpus = "1"
slog = "2"
slog-scope = "4"
slog-stdlog = "4"
slog-term = "2"

[features]
default = []
pool = [
  'r2d2',
  'scheduled-thread-pool',
]
postgresql = [
  'postgres',
  'pool',
]
redis_cluster = [
  'redis/cluster',
  'pool',
]
redis_default = [
  'redis/default',
  'pool',
]
