[package]
name = 'salak_factory'
version = '0.1.4'
authors = ['Daniel Yu <leptonyu@gmail.com>']
edition = '2018'
license = 'MIT'
description = 'Salak factory to package initialization.'
documentation = 'https://docs.rs/salak_factory/'
repository = 'https://github.com/leptonyu/salak.rs'
homepage = 'https://github.com/leptonyu/salak.rs'
readme = 'README.md'
keywords = [
    'configuration',
    'config',
    'settings',
    'env',
    'environment',
]
categories = ['config']
[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    '--cfg',
    'docsrs',
]

[package.metadata.playground]
all-features = true

[dependencies.salak]
path = '..'
version = '^0.8'

[dependencies.postgres]
version = '0.19'
optional = true

[dependencies.redis]
version = '0.20'
optional = true

[dependencies.r2d2]
version = '^0.8'
optional = true

[dependencies.scheduled-thread-pool]
version = '^0.2'
optional = true

[dependencies.tracing-subscriber]
version = '^0.2'
optional = true

[dependencies.tracing-log]
version = '^0.1'
optional = true

[dependencies.tracing]
version = '^0.1'
optional = true

[dependencies.log]
version = '^0.4'
optional = true

[dependencies.chrono]
version = '^0.4'
optional = true

[dependencies.rtrb]
version = '^0.1'
optional = true

[dev-dependencies]
num_cpus = "1"
env_logger = "0.8"
fern = "0.6"
log4rs = "1"
slog = "2"
slog-term = "2"
slog-scope = "4"
slog-stdlog = "4"

[features]
default = []
enable_pool = [
    'r2d2',
    'scheduled-thread-pool',
]
enable_redis = [
    'redis/default',
    'enable_pool',
]
enable_redis_cluster = [
    'redis/cluster',
    'enable_pool',
]
enable_postgres = [
    'postgres',
    'enable_pool',
]
enable_log = ['tracing-log', 'tracing-subscriber', 'tracing' , 'log', 'chrono', 'rtrb']
