name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: | 
        cargo test --verbose
        cargo test --no-default-features --lib --verbose 
        cargo test --no-default-features --lib --verbose --features=enable_log
        cargo test --no-default-features --lib --verbose --features=enable_args
        cargo test --no-default-features --lib --verbose --features=enable_toml
